In [57]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [58]:
import torchvision
import torchvision.transforms as transforms
torch.set_printoptions(linewidth=120)

In [59]:
train_set=torchvision.datasets.FashionMNIST(
    root='./data/FashionMNIST',train=True,download=True,transform=transforms.Compose([transforms.ToTensor()])
)

C:\Users\varun\anaconda3\lib\site-packages\torchvision\datasets\mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [109]:
train_loader=torch.utils.data.DataLoader(train_set,batch_size=100)

In [61]:
import numpy as np
import matplotlib.pyplot as plt

In [110]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        #convulution layer
        self.conv1=nn.Conv2d(in_channels=1,out_channels=6,kernel_size=5)
        self.conv2=nn.Conv2d(in_channels=6,out_channels=12,kernel_size=5)
        #linear layer
        self.fc1=nn.Linear(in_features=12*4*4,out_features=120)
        self.fc2=nn.Linear(in_features=120,out_features=60)
        self.out=nn.Linear(in_features=60,out_features=10)


    def forward(self,t):
        #input layer
        t=t
        #conv layer
        t=self.conv1(t)
        t=F.relu(t)
        t=F.max_pool2d(t,kernel_size=2,stride=2)
        t=self.conv2(t)
        t=F.relu(t)
        t=F.max_pool2d(t,kernel_size=2,stride=2)
        #4th hidden layer
        t=t.reshape(-1,12*4*4)
        t=self.fc1(t)
        t=F.relu(t)
        #5th hidden layer
        t=self.fc2(t)
        t=F.relu(t)
        #6th layer
        t=self.out(t)
        return t


In [77]:
torch.set_grad_enabled(False)

In [111]:
net=Network()

In [79]:
sample=next(iter(train_set))
image,label=sample

In [80]:
image.shape

torch.Size([1, 28, 28])

In [81]:
image.unsqueeze(0).shape #ceate batch

torch.Size([1, 1, 28, 28])

In [83]:
pred=net(image.unsqueeze(0)) #passing to network

C:\Users\varun\anaconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


In [84]:
pred

tensor([[-0.0842, -0.0105,  0.0530,  0.0057, -0.1250,  0.1624,  0.1088,  0.0595,  0.0442,  0.0831]])

In [85]:
pred.shape

torch.Size([1, 10])

In [86]:
label

9

In [87]:
pred.argmax(dim=1)

tensor([5])

In [88]:
F.softmax(pred,dim=1).sum()

tensor(1.0000)

In [89]:
F.softmax(pred,dim=1)

tensor([[0.0889, 0.0957, 0.1020, 0.0973, 0.0854, 0.1138, 0.1079, 0.1027, 0.1011, 0.1051]])

In [90]:
net1=Network()


In [91]:
net1(image.unsqueeze(0))

tensor([[-0.0670,  0.0708, -0.0659,  0.1329, -0.0965, -0.0978,  0.1457, -0.0373, -0.1386,  0.0830]])

In [92]:
print(torch.__version__)

1.9.0


In [93]:
batch=next(iter(train_loader))
images,labels=batch

In [94]:
images.shape

torch.Size([10, 1, 28, 28])

In [95]:
labels.shape

torch.Size([10])

In [97]:
preds=net(images)

In [98]:
preds.shape

torch.Size([10, 10])

In [99]:
preds

tensor([[-0.0842, -0.0105,  0.0530,  0.0057, -0.1250,  0.1624,  0.1088,  0.0595,  0.0442,  0.0831],
        [-0.0893, -0.0135,  0.0533,  0.0021, -0.1228,  0.1574,  0.1047,  0.0643,  0.0485,  0.0839],
        [-0.0843, -0.0118,  0.0493,  0.0042, -0.1176,  0.1544,  0.1095,  0.0626,  0.0389,  0.0771],
        [-0.0887, -0.0109,  0.0532,  0.0049, -0.1187,  0.1595,  0.1100,  0.0631,  0.0416,  0.0771],
        [-0.0886, -0.0117,  0.0540,  0.0041, -0.1184,  0.1572,  0.1047,  0.0590,  0.0415,  0.0785],
        [-0.0879, -0.0155,  0.0532,  0.0009, -0.1247,  0.1572,  0.1046,  0.0659,  0.0439,  0.0811],
        [-0.0876, -0.0147,  0.0524,  0.0043, -0.1289,  0.1598,  0.1068,  0.0663,  0.0477,  0.0832],
        [-0.0853, -0.0120,  0.0543,  0.0009, -0.1217,  0.1611,  0.1100,  0.0633,  0.0431,  0.0815],
        [-0.0844, -0.0150,  0.0495,  0.0080, -0.1248,  0.1537,  0.1027,  0.0594,  0.0443,  0.0773],
        [-0.0805, -0.0131,  0.0501,  0.0077, -0.1345,  0.1555,  0.1051,  0.0618,  0.0479,  0.0796]])

In [100]:
preds.argmax(dim=1)

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [101]:
labels

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [103]:
d=preds.argmax(dim=1).eq(labels)

In [104]:
d.sum()

tensor(2)

In [105]:
torch.set_grad_enabled(True)

In [108]:
def get_num_correct(preds,labels):
    return preds.argmax(dim=1).eq(labels).sum().item()

In [112]:
loss=F.cross_entropy(preds,labels)
loss.item() #loss

2.3034956455230713

In [113]:
print(net.conv1.weight.grad)

None
