In [5]:
import torch
import numpy as np

In [9]:
t=torch.tensor(2)
type(t)

torch.Tensor

In [10]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [11]:
device=torch.device('cuda:0')

In [12]:
device

device(type='cuda', index=0)

In [13]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1,2,3])
t3=t1+t2

In [14]:
t3

tensor([2, 4, 6])

In [24]:
data=np.array([1,2,3])
type(data)

numpy.ndarray

In [25]:
t1=torch.tensor(data)

In [26]:
t2=torch.Tensor(data)

In [27]:
t3=torch.as_tensor(data)

In [28]:
t4=torch.from_numpy(data)

In [20]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.rand(2,2)

tensor([[0.9224, 0.8284],
        [0.4253, 0.9629]])

In [29]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.int32
torch.float32
torch.int32
torch.int32


In [31]:
torch.get_default_dtype()

torch.float32

In [32]:
t5=torch.tensor(np.array([1,2,3]),dtype=torch.float64)
t5

tensor([1., 2., 3.], dtype=torch.float64)

In [33]:
data[0]=0
data[1]=0
data[2]=0

In [34]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
