In [1]:
import torch

In [2]:
t=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [3]:
t.size()

torch.Size([3, 4])

In [4]:
len(t.shape)

2

In [6]:
torch.tensor(t.shape).prod()

tensor(12)

In [8]:
t.numel()

12

In [9]:
a=t.reshape(12,1)

In [10]:
b=t.reshape(6,2)

In [11]:
c=t.reshape(4,3)

In [13]:
a

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [14]:
b

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [15]:
c

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [16]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [17]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [18]:
def flat(t):
    t=t.reshape(1,-1)
    t=t.squeeze()
    return t

In [19]:
flat(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])